Indir: "/data/manke/processing1/pipegrp/smRNAPipeline/Analysis_3467_Kim_Denboba/Results"
Outdir: "/data/manke/processing1/pipegrp/smRNAPipeline/Analysis_3467_Kim_Denboba/Results/DEseq2_TEsmall/"
MetaData: "/data/manke/processing1/pipegrp/smRNAPipeline/Analysis_3467_Kim_Denboba/Results/metaInfo.tsv"
smallestGroupSize: 3
DeseqEnv: "envs/env_deseq2.yaml"
